--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/noobie/012.jpg"

-- Special
background="#030F18"
foreground="#9ed0e8"
cursor="#9ed0e8"

-- Colors
color0="#030F18"
color1="#4A6A78"
color2="#0F588A"
color3="#196DA7"
color4="#187CBE"
color5="#2597DB"
color6="#52A9D2"
color7="#9ed0e8"
color8="#6e91a2"
color9="#4A6A78"
color10="#0F588A"
color11="#196DA7"
color12="#187CBE"
color13="#2597DB"
color14="#52A9D2"
color15="#9ed0e8"
