# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/noobie/012.jpg'

# Special
background='#030F18'
foreground='#9ed0e8'
cursor='#9ed0e8'

# Colors
color0='#030F18'
color1='#4A6A78'
color2='#0F588A'
color3='#196DA7'
color4='#187CBE'
color5='#2597DB'
color6='#52A9D2'
color7='#9ed0e8'
color8='#6e91a2'
color9='#4A6A78'
color10='#0F588A'
color11='#196DA7'
color12='#187CBE'
color13='#2597DB'
color14='#52A9D2'
color15='#9ed0e8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
